[package]
name = "rd-132328"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lwrgl = { path = "../lwrgl", version = "0.1.0" }
rand = "0.8"
flate2 = "1.0"
lazy_static = "1.4.0"
image = "0.24"
